### SignUp (

http POST {{API_BASE}}/api/v1/auth/userSignUp \
  name="Jackson Win" \
  email="jack@example.com" \
  "Content-Type: application/json"

### Login 

http POST {{API_BASE}}/api/v1/auth/signIn \
  name="Jackson Win" \
  password="password" \
  "Content-Type: application/json"