spring:
  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  flyway:
    enabled: true
  application:
    name: jwt-auth.with-refresh-token
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: jackson14042004@gmail.com
    password: fybnhqmmhlwwzgvf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  private-key: classpath:jwt/private.pem
  public-key: classpath:jwt/public.pem
  ttl: 15m